#:schema https://www.unpkg.com/wrangler/config-schema.json
# ref: <https://developers.cloudflare.com/workers/wrangler/configuration/>

compatibility_date = "2026-03-27"
compatibility_flags = ["nodejs_compat"]
main = "./src/index.ts"
minify = true
name = "github-bot"
send_metrics = false
upload_source_maps = true

[observability]
enabled = true

[vars]
APP_ID = "1022004"
