name: Auto Approve

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  delete-cancelled-runs:
    name: Delete Cancelled Runs
    permissions:
      actions: write
    runs-on: ubuntu-latest
    steps:
      - name: Delete Cancelled Runs
        uses: liblaf/actions/delete-cancelled-runs@main

  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    steps:
      - name: Auto Approve Release Please
        run: npx @liblaf/github-bot-cli approve-all
        env:
          INPUT_APP_ID: ${{ secrets.GH_APP_ID }}
          INPUT_LABELS: |-
            autorelease: pending
          INPUT_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}
          INPUT_TOKEN: ${{ secrets.GH_PAT }}

  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - name: Auto Approve Renovate
        run: npx @liblaf/github-bot-cli approve-all
        env:
          INPUT_APP_ID: ${{ secrets.GH_APP_ID }}
          INPUT_AUTHORS: |-
            renovate[bot]
          INPUT_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}
          INPUT_TOKEN: ${{ secrets.GH_PAT }}
