name: Auto Approve

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  delete-cancelled-runs:
    name: Delete Cancelled Runs
    permissions:
      actions: write
    runs-on: ubuntu-latest
    steps:
      - name: Delete Cancelled Runs
        uses: liblaf/actions/delete-cancelled-runs@main

  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    steps:
      - name: Auto Approve Release Please
        uses: liblaf/actions-ts/all-repos-approve@dist
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          labels: "autorelease: pending"
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          token: ${{ secrets.GH_PAT }}

  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - name: Auto Approve Renovate
        uses: liblaf/actions-ts/all-repos-approve@dist
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          authors: renovate[bot]
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          token: ${{ secrets.GH_PAT }}
