name: Bot > Sync Repo Settings

run-name: >-
  ${{ github.workflow }} > ${{ github.event.client_payload.repository }}

on:
  repository_dispatch:
    types:
      - repository.created
      - schedule.weekly
      - sync-repo-settings

env:
  FORCE_COLOR: 1
  OWNER: ${{ github.event.client_payload.owner }}
  REPO: ${{ github.event.client_payload.repo }}
  REPOSITORY: ${{ github.event.client_payload.repository }}

concurrency:
  group: >-
    ${{ github.workflow }} > ${{ github.event.client_payload.repository }}
  cancel-in-progress: false

jobs:
  actions:
    name: Actions
    runs-on: ubuntu-latest
    steps:
      - name: Set default workflow permissions
        # ref: <https://docs.github.com/en/rest/actions/permissions?apiVersion=2026-03-10#set-default-workflow-permissions-for-a-repository>
        # "Administration" repository permissions (write)
        # Note: `can_approve_pull_request_reviews` grants permission to create pull requests and submit approving reviews; set to `true` to enable GitHub Actions to create pull requests.
        run: >-
          gh api '/repos/${{ env.REPOSITORY }}/actions/permissions/workflow'
          --field default_workflow_permissions='read' --field
          can_approve_pull_request_reviews=true --method PUT
        env:
          GH_TOKEN: ${{ secrets.SYNC_REPO_SETTINGS_TOKEN }}

  environments:
    name: Environment > ${{ matrix.environment }}
    runs-on: ubuntu-latest
    environment:
      name: ${{ matrix.environment }}
      deployment: false
    env:
      GH_TOKEN: ${{ secrets.SYNC_REPO_SETTINGS_TOKEN }}
    steps:
      - name: Create environment
        # ref: <https://docs.github.com/en/rest/deployments/environments?apiVersion=2026-03-10#create-or-update-an-environment>
        # "Administration" repository permissions (write)
        run: >-
          gh api '/repos/${{ env.REPOSITORY }}/environments/${{
          matrix.environment }}' --method PUT
      - name: Set App ID & private key
        run: |-
          # migration
          gh variable delete APP_ID --env '${{ matrix.environment }}' --repo '${{ env.REPOSITORY }}' || true
          gh secret delete PRIVATE_KEY --env '${{ matrix.environment }}' --repo '${{ env.REPOSITORY }}' || true
          if [[ -n '${{ vars.APP_CLIENT_ID }}' ]]; then
            gh variable set APP_CLIENT_ID --env '${{ matrix.environment }}' --body '${{ vars.APP_CLIENT_ID }}' --repo '${{ env.REPOSITORY }}'
            gh secret set APP_PRIVATE_KEY --env '${{ matrix.environment }}' --body "$APP_PRIVATE_KEY" --repo '${{ env.REPOSITORY }}'
          fi
        env:
          APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
    strategy:
      matrix:
        environment:
          - approve
          - copier
          - mega-linter
          - npm
          - pypi
          - release-please

  gh-pages:
    name: GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Setup GitHub Pages
        uses: liblaf/actions/setup-pages@30c85b7c83d5db558c3113c5a7297837f6fe4904 # v1
        with:
          repository: ${{ env.REPOSITORY }}
          token: ${{ secrets.SYNC_REPO_SETTINGS_TOKEN }}

  immutable-releases:
    name: Disable Immutable Releases
    runs-on: ubuntu-latest
    steps:
      - name: Disable immutable releases
        # ref: <https://docs.github.com/en/rest/repos/repos?apiVersion=2026-03-10#disable-immutable-releases>
        # "Administration" repository permissions (write)
        run: >-
          gh api '/repos/${{ env.REPOSITORY }}/immutable-releases' --method
          DELETE
        env:
          GH_TOKEN: ${{ secrets.SYNC_REPO_SETTINGS_TOKEN }}

  label:
    name: Label
    runs-on: ubuntu-latest
    steps:
      # TODO: remove download labels until <https://github.com/Financial-Times/github-label-sync/issues/193> is resolved
      - name: Download labels
        run: >-
          wget --output-document='labels.yaml'
          'https://raw.githubusercontent.com/${{ env.OWNER
          }}/.github/main/.github/labels.yaml'
      - name: Sync labels
        run: >-
          npx github-label-sync --access-token '${{
          secrets.SYNC_REPO_SETTINGS_TOKEN }}' --labels 'labels.yaml'
          --allow-added-labels '${{ env.REPOSITORY }}'

  repo:
    name: Repo
    runs-on: ubuntu-latest
    steps:
      - name: Edit repository settings
        run: >-
          gh repo edit '${{ env.REPOSITORY }}' --allow-update-branch
          --delete-branch-on-merge --enable-auto-merge --enable-discussions
          --enable-issues --enable-merge-commit=false --enable-projects=false
          --enable-rebase-merge=false --enable-secret-scanning
          --enable-secret-scanning-push-protection --enable-squash-merge
          --enable-wiki=false
        env:
          GH_TOKEN: ${{ secrets.SYNC_REPO_SETTINGS_TOKEN }}

  ruleset:
    name: Ruleset
    runs-on: ubuntu-latest
    steps:
      - name: Import ruleset
        # TODO: switch to gh cli until <https://github.com/cli/cli/issues/8019> is resolved
        uses: liblaf/actions/ruleset-import@30c85b7c83d5db558c3113c5a7297837f6fe4904 # v1
        with:
          name: main
          source-repository: ${{ env.OWNER }}/.github
          target-repository: ${{ env.REPOSITORY }}
          token: ${{ secrets.SYNC_REPO_SETTINGS_TOKEN }}
