name: (Webhook) pull_request

run-name: >-
  ${{ format('{0}: {1}/{2}#{3}', github.workflow, inputs.owner || github.event.client_payload.repositories.owner.login, inputs.repo || github.event.client_payload.repositories.name, inputs.number || github.event.client_payload.pull_request.number) }}

on:
  workflow_call:
    inputs:
      owner:
        required: true
        type: string
      repo:
        required: true
        type: string
      number:
        required: true
        type: number
  workflow_dispatch:
    inputs:
      owner:
        description: owner
        required: true
        default: liblaf
        type: string
      repo:
        description: repo
        required: true
        type: string
      number:
        description: pull request number
        required: true
        type: number
  repository_dispatch:
    types:
      - pull_request_review.dismissed
      # ref: <https://docs.github.com/en/actions/reference/workflows-and-actions/events-that-trigger-workflows#pull_request>
      - pull_request.opened
      - pull_request.reopened
      - pull_request.synchronize

concurrency:
  group: >-
    ${{ format('{0}: {1}/{2}#{3}', github.workflow, inputs.owner || github.event.client_payload.repositories.owner.login, inputs.repo || github.event.client_payload.repositories.name, inputs.number || github.event.client_payload.pull_request.number) }}
  cancel-in-progress: true

jobs:
  pre:
    name: Pre
    permissions:
      actions: write
    runs-on: ubuntu-latest
    outputs:
      should-skip: ${{ steps.pre.outputs.should-skip }}
    steps:
      - id: pre
        name: Pre
        uses: liblaf/actions-ts/pre@dist

  inputs:
    name: Inputs
    runs-on: ubuntu-latest
    outputs:
      full-name: ${{ steps.inputs.outputs.full-name }}
      number: ${{ steps.inputs.outputs.number }}
      owner: ${{ steps.inputs.outputs.owner }}
      repo: ${{ steps.inputs.outputs.repo }}
    steps:
      - id: inputs
        name: Parse Inputs
        run: |-
          case '${{ github.event_name }}' in
            'repository_dispatch')
              printf 'full-name=%s\n' '${{ github.event.client_payload.repository.full_name }}' >> "$GITHUB_OUTPUT"
              printf 'number=%s\n' '${{ github.event.client_payload.number }}' >> "$GITHUB_OUTPUT"
              printf 'owner=%s\n' '${{ github.event.client_payload.repository.owner.login }}' >> "$GITHUB_OUTPUT"
              printf 'repo=%s\n' '${{ github.event.client_payload.repository.name }}' >> "$GITHUB_OUTPUT"
              ;;
            'workflow_call' | 'workflow_dispatch')
              printf 'full-name=%s\n' '${{ inputs.owner }}/${{ inputs.repo }}' >> "$GITHUB_OUTPUT"
              printf 'number=%s\n' '${{ inputs.number }}' >> "$GITHUB_OUTPUT"
              printf 'owner=%s\n' '${{ inputs.owner }}' >> "$GITHUB_OUTPUT"
              printf 'repo=%s\n' '${{ inputs.repo }}' >> "$GITHUB_OUTPUT"
              ;;
            *)
              echo '::error::Unsupported event name: ${{ github.event_name }}'
              ;;
          esac

  auto-merge:
    name: Auto-Merge
    needs:
      - inputs
    runs-on: ubuntu-latest
    steps:
      - id: auth
        name: Authenticate
        uses: liblaf/actions-ts/authenticate@dist
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          owner: ${{ needs.inputs.outputs.owner }}
          repositories: ${{ needs.inputs.outputs.repo }}
      - name: Auto-Merge Renovate
        uses: liblaf/actions/pr-label@main
        with:
          add-label: automerge
          app: renovate
          repo: ${{ needs.inputs.outputs.full-name }}
          token: ${{ steps.auth.outputs.token }}

  auto-approve:
    name: Auto Approve
    needs:
      - inputs
    runs-on: ubuntu-latest
    steps:
      - name: Auto Approve Renovate
        uses: liblaf/actions-ts/approve@dist
        with:
          authors: renovate[bot]
          pull-number: ${{ needs.inputs.outputs.number }}
          repository: ${{ needs.inputs.outputs.full-name }}
          token: ${{ secrets.GH_PAT }}
