# ref: <https://docs.github.com/en/webhooks/webhook-events-and-payloads#repository>

name: repository.created

run-name: >-
  repository.created: ${{ github.event.client_payload.repository.full_name }}

on:
  repository_dispatch:
    types:
      - repository.created

jobs:
  actions:
    name: Actions
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.event.client_payload.repository.full_name }}/${{ github.workflow }}/actions
      cancel-in-progress: true
    steps:
      - name: Set Default Workflow Permissions
        # ref: <https://docs.github.com/en/rest/actions/permissions#set-default-workflow-permissions-for-a-repository>
        run: >-
          gh api '/repos/${{ github.event.client_payload.repository.full_name }}/actions/permissions/workflow'
          --field default_workflow_permissions='read'
          --field can_approve_pull_request_reviews=true
          --method PUT
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}

  copier:
    name: Copier
    permissions:
      contents: write
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.event.client_payload.repository.full_name }}/${{ github.workflow }}/copier
      cancel-in-progress: true
    steps:
      - id: auth
        name: Auth App
        uses: liblaf/actions/auth-app@main
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          owner: ${{ github.event.client_payload.repository.owner.login }}
          repositories: ${{ github.event.client_payload.repository.name }}
      - id: branches
        name: Get Branches
        run: |-
          n_branches="$(gh api "/repos/${{ github.event.client_payload.repository.full_name }}/branches" --jq 'length')"
          echo "n_branches=$n_branches" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.auth.outputs.token }}
      - if: ${{ steps.branches.outputs.n_branches > 0 }}
        name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.client_payload.repository.full_name }}
          token: ${{ steps.auth.outputs.token }}
      - if: ${{ steps.branches.outputs.n_branches > 0 }}
        name: Copier Update
        uses: liblaf/actions/copier-update@main
      - if: ${{ steps.branches.outputs.n_branches > 0 }}
        name: Commit
        uses: liblaf/actions/commit@main
        with:
          add-options: --verbose --all
          message: "chore(copier): update from template"
          owner: ${{ github.event.client_payload.repository.owner.login }}
          repository: ${{ github.event.client_payload.repository.name }}
          token: ${{ steps.auth.outputs.token }}

  label:
    name: Label
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.event.client_payload.repository.full_name }}/${{ github.workflow }}/label
      cancel-in-progress: true
    steps:
      - id: auth
        name: Auth App
        uses: liblaf/actions/auth-app@main
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          owner: ${{ github.event.client_payload.repository.owner.login }}
          repositories: ${{ github.event.client_payload.repository.name }}
        # TODO: remove download labels until <https://github.com/Financial-Times/github-label-sync/issues/193> is resolved
      - name: Download Labels
        run: >-
          wget --output-document='labels.yaml'
          'https://raw.githubusercontent.com/${{ github.event.client_payload.repository.owner.login }}/.github/main/.github/labels.yaml'
      - name: GitHub Label Sync
        run: >-
          npx github-label-sync
          --access-token '${{ steps.auth.outputs.token }}'
          --labels 'labels.yaml'
          --allow-added-labels
          '${{ github.event.client_payload.repository.full_name }}'

  repo:
    name: Repo
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.event.client_payload.repository.full_name }}/${{ github.workflow }}/repo
      cancel-in-progress: true
    steps:
      - name: Edit Repository Setttings
        run: >-
          gh repo edit '${{ github.event.client_payload.repository.full_name }}'
          --allow-update-branch
          --delete-branch-on-merge
          --enable-auto-merge
          --enable-discussions
          --enable-issues
          --enable-merge-commit=false
          --enable-rebase-merge=false
          --enable-squash-merge
          --enable-wiki=false
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}

  ruleset:
    name: Ruleset
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.event.client_payload.repository.full_name }}/${{ github.workflow }}/ruleset
      cancel-in-progress: true
    steps:
      - name: Ruleset Import
        # TODO: switch to gh cli until <https://github.com/cli/cli/issues/8019> is resolved
        uses: liblaf/actions/ruleset-import@main
        with:
          repo: ${{ github.event.client_payload.repository.full_name }}
          token: ${{ secrets.GH_PAT }}
          source-repo: ${{ github.event.client_payload.repository.owner.login }}/.github
          source-ruleset-id: 3407904

  secrets:
    name: Secrets
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.event.client_payload.repository.full_name }}/${{ github.workflow }}/secrets
      cancel-in-progress: true
    steps:
      - name: Create or Update Secrets
        run: |-
          function secret-set() {
            gh secret --repo '${{ github.event.client_payload.repository.full_name }}' set "$1" --body "$2"
          }

          secret-set CARGO_REGISTRY_TOKEN '${{ secrets.CARGO_REGISTRY_TOKEN }}'
          secret-set GH_APP_ID '${{ secrets.GH_APP_ID }}'
          secret-set GH_APP_PRIVATE_KEY '${{ secrets.GH_APP_PRIVATE_KEY }}'
          secret-set GH_PAT '${{ secrets.GH_PAT }}'
          secret-set NPM_TOKEN '${{ secrets.NPM_TOKEN }}'
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
