name: Schedule > Sync Repo Settings

on:
  schedule:
    - cron: "0 0 * * 0" # Runs at 00:00, only on Sunday
  workflow_dispatch:

jobs:
  sync-repo-settings:
    name: Sync Repo Settings
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install Dependencies
        run: bun install
      - name: Sync Repo Settings
        run: bun run 'scripts/schedule-settings.ts'
        env:
          GITHUB_TOKEN: ${{ github.token }}
