name: Sync Repo Settings

on:
  workflow_dispatch:
    inputs:
      owner:
        description: owner
        required: true
        type: string
      repo:
        description: repo
        required: true
        type: string

env:
  FORCE_COLOR: 1

jobs:
  actions:
    name: Actions
    runs-on: ubuntu-latest
    steps:
      - name: Set Default Workflow Permissions
        # ref: <https://docs.github.com/en/rest/actions/permissions?apiVersion=2022-11-28#set-default-workflow-permissions-for-a-repository>
        run: >-
          gh api '/repos/${{ inputs.owner }}/${{ inputs.repo }}/actions/permissions/workflow'
          --field default_workflow_permissions='read'
          --field can_approve_pull_request_reviews=true
          --method PUT
        env:
          GH_TOKEN: ${{ secrets.SYNC_REPO_SETTINGS_PAT }}

  env-mega-linter:
    name: Environment > MegaLinter
    environment:
      name: MegaLinter
    runs-on: ubuntu-latest
    steps:
      - name: Create Environment
        run: >-
          gh api '/repos/${{ inputs.owner }}/${{ inputs.repo }}/environments/MegaLinter'
          --method PUT
        env:
          GH_TOKEN: ${{ secrets.SYNC_REPO_SETTINGS_PAT }}
      - name: Set Secrets and Variables
        run: |-
          gh secret set PRIVATE_KEY \
            --body '${{ secrets.PRIVATE_KEY }}' \
            --env 'MegaLinter' \
            --repo '${{ inputs.owner }}/${{ inputs.repo }}'
          gh variable set APP_ID \
            --body '${{ vars.APP_ID }}' \
            --env 'MegaLinter' \
            --repo '${{ inputs.owner }}/${{ inputs.repo }}'

  label:
    name: Label
    runs-on: ubuntu-latest
    steps:
      # TODO: remove download labels until <https://github.com/Financial-Times/github-label-sync/issues/193> is resolved
      - name: Download Labels
        run: >-
          wget --output-document='labels.yaml'
          'https://raw.githubusercontent.com/${{ inputs.owner }}/.github/main/.github/labels.yaml'
      - name: GitHub Label Sync
        run: >-
          npx github-label-sync
          --access-token '${{ secrets.SYNC_REPO_SETTINGS_PAT }}'
          --labels 'labels.yaml'
          --allow-added-labels
          '${{ inputs.owner }}/${{ inputs.repo }}'

  repo:
    name: Repo
    runs-on: ubuntu-latest
    steps:
      - name: Edit Repository Settings
        run: >-
          gh repo edit '${{ inputs.owner }}/${{ inputs.repo }}'
          --allow-update-branch
          --delete-branch-on-merge
          --enable-auto-merge
          --enable-discussions
          --enable-issues
          --enable-merge-commit=false
          --enable-rebase-merge=false
          --enable-squash-merge
          --enable-wiki=false
        env:
          GH_TOKEN: ${{ secrets.SYNC_REPO_SETTINGS_PAT }}

  ruleset:
    name: Ruleset
    runs-on: ubuntu-latest
    steps:
      - name: Ruleset Import
        # TODO: switch to gh cli until <https://github.com/cli/cli/issues/8019> is resolved
        uses: liblaf/actions/ruleset-import@dist
        with:
          name: main
          source-repository: ${{ inputs.owner }}/.github
          target-repository: ${{ inputs.owner }}/${{ inputs.repo }}
          token: ${{ secrets.SYNC_REPO_SETTINGS_PAT }}
